spring:
  application:
    name: web-hub

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/web_hub
    driver-class-name: org.postgresql.Driver
  username: postgres
  password: 1234567@

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: stanleyshadrack213@gmail.com
    password: hozpltwxbixcenpn
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true


jwt:
  secret: JK1pNC7VMEhjqqK9CMypsw0ybDLJtzDDLk3N266Ld/k=

  expiration: 86400000

app:
  admin:
    email: shazanaombonya@gmail.com
    password: 12345
