spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web_hub
    username: postgres
    password: smartcode
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
